# Generated by Django 3.1.2 on 2020-10-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercandise_title', models.CharField(max_length=128)),
                ('merchandise_descript', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Storege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storege_title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oredr_date', models.DateField(auto_now=True)),
                ('order_depart_date', models.DateField()),
                ('order_prepare', models.BooleanField()),
                ('order_depart', models.BooleanField()),
                ('order_connect_mer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storege.merchandise')),
                ('orderr_connect_stor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storege.storege')),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='merchandise_conect',
            field=models.ManyToManyField(through='storege.Order', to='storege.Storege'),
        ),
    ]
