# Generated by Django 3.1.2 on 2020-10-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storege', '0002_auto_20201008_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredr_date',
            new_name='order_date',
        ),
    ]
