# Generated by Django 3.1.2 on 2020-10-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storege', '0003_auto_20201008_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderr_connect_stor',
            field=models.ForeignKey(db_column='storege_admin', on_delete=django.db.models.deletion.CASCADE, related_name='actionresult', to='storege.storege'),
        ),
    ]
